"""added new columns

Revision ID: 371be38772ef
Revises: 
Create Date: 2025-04-24 18:41:32.519545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '371be38772ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
